application:
  port: 8080
database:
  host: localhost
  port: 5432
  database_name: newsletter
  username: postgres
  password: password
email_client:
  base_url: localhost
  sender_email: test@gmail.com
  auth_token: test-token
  timeout_milliseconds: 10000
